<?php
/**
 * Model pricing data (USD per 1M tokens).
 *
 * Shipped as a guarded PHP file (not a public .json) so the data cannot be
 * downloaded directly over HTTP on ANY web server (Apache, nginx, Caddy,
 * LiteSpeed, ...). A direct request executes PHP and returns nothing; the
 * plugin loads it via include from the filesystem. Auto-generated by
 * bin/gen-pricing.php — do not edit by hand.
 */

if ( ! defined( "ABSPATH" ) ) { exit; }

return array (
  'source' => 'QuantumNous/new-api setting/ratio_setting/model_ratio.go + cache_ratio.go',
  'generated' => '2026-06-23T20:11:36+00:00',
  'note' => 'USD per 1M tokens. input$=modelRatio*2; output$=input$*completionRatio. cache_ratios = cached-input discount multiplier (cached_tokens billed at input$*ratio). Update by editing this file or re-running bin/gen-pricing.php.',
  'fallback' => 
  array (
    'input' => 3,
    'output' => 15,
  ),
  'models' => 
  array (
    'gemini-2.5-flash-preview-04-17-nothinking' => 
    array (
      'input' => 0.15,
      'output' => 0.6,
    ),
    'gemini-2.5-flash-preview-05-20-nothinking' => 
    array (
      'input' => 0.15,
      'output' => 0.6,
    ),
    'gpt-4o-mini-realtime-preview-2024-12-17' => 
    array (
      'input' => 0.6,
      'output' => 2.4,
    ),
    'gemini-2.5-flash-preview-04-17-thinking' => 
    array (
      'input' => 0.15,
      'output' => 3.5,
    ),
    'gemini-2.5-flash-preview-05-20-thinking' => 
    array (
      'input' => 0.15,
      'output' => 3.5,
    ),
    'qwen/qwen3-coder-480b-a35b-instruct-fp8' => 
    array (
      'input' => 1.6,
      'output' => 1.6,
    ),
    'claude-3-7-sonnet-20250219-thinking' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'gemini-2.5-flash-lite-preview-06-17' => 
    array (
      'input' => 0.1,
      'output' => 0.4,
    ),
    'gpt-4o-realtime-preview-2024-10-01' => 
    array (
      'input' => 5,
      'output' => 20,
    ),
    'gpt-4o-realtime-preview-2024-12-17' => 
    array (
      'input' => 5,
      'output' => 20,
    ),
    'qwen/qwen3-235b-a22b-thinking-2507' => 
    array (
      'input' => 1.2,
      'output' => 1.2,
    ),
    'qwen/qwen3-235b-a22b-instruct-2507' => 
    array (
      'input' => 0.6,
      'output' => 0.6,
    ),
    'o4-mini-deep-research-2025-06-26' => 
    array (
      'input' => 2,
      'output' => 2,
    ),
    'gpt-4o-audio-preview-2024-10-01' => 
    array (
      'input' => 2.5,
      'output' => 10,
    ),
    'gemini-2.5-flash-preview-04-17' => 
    array (
      'input' => 0.15,
      'output' => 3.5,
    ),
    'gemini-2.5-flash-preview-05-20' => 
    array (
      'input' => 0.15,
      'output' => 3.5,
    ),
    'gemini-robotics-er-1.5-preview' => 
    array (
      'input' => 0.3,
      'output' => 2.5,
    ),
    '360gpt-turbo-responsibility-8k' => 
    array (
      'input' => 1.7144,
      'output' => 1.7144,
    ),
    'llama-3-sonar-small-32k-online' => 
    array (
      'input' => 0.4,
      'output' => 0.4,
    ),
    'llama-3-sonar-large-32k-online' => 
    array (
      'input' => 2,
      'output' => 2,
    ),
    'nousresearch/hermes-4-405b-fp8' => 
    array (
      'input' => 1.6,
      'output' => 1.6,
    ),
    'gpt-4o-mini-realtime-preview' => 
    array (
      'input' => 0.6,
      'output' => 2.4,
    ),
    'gemini-2.5-pro-preview-03-25' => 
    array (
      'input' => 1.25,
      'output' => 10,
    ),
    'llama-3-sonar-small-32k-chat' => 
    array (
      'input' => 0.4,
      'output' => 0.4,
    ),
    'llama-3-sonar-large-32k-chat' => 
    array (
      'input' => 2,
      'output' => 2,
    ),
    'deepseek-ai/deepseek-r1-0528' => 
    array (
      'input' => 1.6,
      'output' => 1.6,
    ),
    'deepseek-ai/deepseek-v3-0324' => 
    array (
      'input' => 1.6,
      'output' => 1.6,
    ),
    'o3-deep-research-2025-06-26' => 
    array (
      'input' => 10,
      'output' => 40,
    ),
    'gpt-4.5-preview-2025-02-27' => 
    array (
      'input' => 75,
      'output' => 150,
    ),
    'claude-3-5-sonnet-20240620' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'claude-3-5-sonnet-20241022' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'claude-3-7-sonnet-20250219' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'claude-sonnet-4-5-20250929' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'gemini-3.5-flash-extra-low' => 
    array (
      'input' => 1.5,
      'output' => 9,
    ),
    'gpt-4-1106-vision-preview' => 
    array (
      'input' => 10,
      'output' => 20,
    ),
    'o3-mini-2025-01-31-medium' => 
    array (
      'input' => 1.1,
      'output' => 4.4,
    ),
    'claude-3-5-haiku-20241022' => 
    array (
      'input' => 1,
      'output' => 5,
    ),
    'claude-haiku-4-5-20251001' => 
    array (
      'input' => 1,
      'output' => 5,
    ),
    'gemini-2.5-flash-thinking' => 
    array (
      'input' => 0.3,
      'output' => 2.5,
    ),
    'semantic_similarity_s1_v1' => 
    array (
      'input' => 0.143,
      'output' => 0.143,
    ),
    'deepseek-ai/deepseek-v3.1' => 
    array (
      'input' => 1.6,
      'output' => 1.6,
    ),
    'claude-3-sonnet-20240229' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'claude-sonnet-4-20250514' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'claude-opus-4-5-20251101' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'claude-opus-4-6-thinking' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'claude-opus-4-1-20250805' => 
    array (
      'input' => 15,
      'output' => 75,
    ),
    'gemini-2.5-pro-exp-03-25' => 
    array (
      'input' => 1.25,
      'output' => 10,
    ),
    'gpt-4o-realtime-preview' => 
    array (
      'input' => 5,
      'output' => 20,
    ),
    'gpt-4.1-mini-2025-04-14' => 
    array (
      'input' => 0.4,
      'output' => 0.8,
    ),
    'gpt-4.1-nano-2025-04-14' => 
    array (
      'input' => 0.1,
      'output' => 0.2,
    ),
    'o3-mini-2025-01-31-high' => 
    array (
      'input' => 1.1,
      'output' => 4.4,
    ),
    'text-search-ada-doc-001' => 
    array (
      'input' => 20,
      'output' => 20,
    ),
    'claude-3-haiku-20240307' => 
    array (
      'input' => 0.25,
      'output' => 1.25,
    ),
    'gemini-1.5-flash-latest' => 
    array (
      'input' => 0.15,
      'output' => 0.6,
    ),
    'deepseek-ai/deepseek-r1' => 
    array (
      'input' => 1.6,
      'output' => 1.6,
    ),
    'o3-mini-2025-01-31-low' => 
    array (
      'input' => 1.1,
      'output' => 4.4,
    ),
    'gpt-4o-mini-2024-07-18' => 
    array (
      'input' => 0.15,
      'output' => 0.6,
    ),
    'gpt-4-turbo-2024-04-09' => 
    array (
      'input' => 10,
      'output' => 30,
    ),
    'gpt-3.5-turbo-16k-0613' => 
    array (
      'input' => 3,
      'output' => 6,
    ),
    'gpt-3.5-turbo-instruct' => 
    array (
      'input' => 1.5,
      'output' => 3,
    ),
    'claude-opus-4-6-medium' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'claude-opus-4-7-medium' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'claude-3-opus-20240229' => 
    array (
      'input' => 15,
      'output' => 75,
    ),
    'claude-opus-4-20250514' => 
    array (
      'input' => 15,
      'output' => 75,
    ),
    'gemini-3.1-flash-image' => 
    array (
      'input' => 0.5,
      'output' => 60,
    ),
    'command-r-plus-08-2024' => 
    array (
      'input' => 2.5,
      'output' => 10,
    ),
    'o1-preview-2024-09-12' => 
    array (
      'input' => 15,
      'output' => 60,
    ),
    'o4-mini-deep-research' => 
    array (
      'input' => 2,
      'output' => 2,
    ),
    'gpt-5-mini-2025-08-07' => 
    array (
      'input' => 0.25,
      'output' => 2,
    ),
    'gpt-5-nano-2025-08-07' => 
    array (
      'input' => 0.05,
      'output' => 0.4,
    ),
    'claude-opus-4-7-xhigh' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'gemini-1.5-pro-latest' => 
    array (
      'input' => 2.5,
      'output' => 10,
    ),
    'gemini-2.5-flash-lite' => 
    array (
      'input' => 0.1,
      'output' => 0.4,
    ),
    'gemini-3.1-flash-lite' => 
    array (
      'input' => 0.25,
      'output' => 1.5,
    ),
    'embedding-bert-512-v1' => 
    array (
      'input' => 0.143,
      'output' => 0.143,
    ),
    'command-light-nightly' => 
    array (
      'input' => 1,
      'output' => 4,
    ),
    'grok-3-mini-fast-beta' => 
    array (
      'input' => 0.6,
      'output' => 0.6,
    ),
    'gpt-4-vision-preview' => 
    array (
      'input' => 10,
      'output' => 20,
    ),
    'gpt-4o-audio-preview' => 
    array (
      'input' => 2.5,
      'output' => 10,
    ),
    'claude-opus-4-6-high' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'claude-opus-4-7-high' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'gemini-3-flash-agent' => 
    array (
      'input' => 0.5,
      'output' => 3,
    ),
    'gemini-3.5-flash-low' => 
    array (
      'input' => 1.5,
      'output' => 9,
    ),
    'gemini-embedding-001' => 
    array (
      'input' => 0.15,
      'output' => 0.6,
    ),
    'yi-large-rag-preview' => 
    array (
      'input' => 50,
      'output' => 50,
    ),
    'gpt-4-turbo-preview' => 
    array (
      'input' => 10,
      'output' => 30,
    ),
    'gpt-5.3-codex-spark' => 
    array (
      'input' => 1.75,
      'output' => 14,
    ),
    'claude-opus-4-6-max' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'claude-opus-4-6-low' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'claude-opus-4-7-max' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'claude-opus-4-7-low' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'gemini-3.1-pro-high' => 
    array (
      'input' => 4,
      'output' => 18,
    ),
    'zai-org/glm-4.5-fp8' => 
    array (
      'input' => 1.6,
      'output' => 1.6,
    ),
    'openai/gpt-oss-120b' => 
    array (
      'input' => 1,
      'output' => 1,
    ),
    'gpt-oss-120b-medium' => 
    array (
      'input' => 1,
      'output' => 1,
    ),
    'gpt-4-1106-preview' => 
    array (
      'input' => 10,
      'output' => 20,
    ),
    'gpt-4-0125-preview' => 
    array (
      'input' => 10,
      'output' => 20,
    ),
    'gpt-4.1-2025-04-14' => 
    array (
      'input' => 2,
      'output' => 4,
    ),
    'o1-mini-2024-09-12' => 
    array (
      'input' => 1.1,
      'output' => 4.4,
    ),
    'o3-mini-2025-01-31' => 
    array (
      'input' => 1.1,
      'output' => 4.4,
    ),
    'o4-mini-2025-04-16' => 
    array (
      'input' => 1.1,
      'output' => 1.1,
    ),
    'gpt-3.5-turbo-0613' => 
    array (
      'input' => 1.5,
      'output' => 3,
    ),
    'gpt-3.5-turbo-1106' => 
    array (
      'input' => 1,
      'output' => 2,
    ),
    'gpt-3.5-turbo-0125' => 
    array (
      'input' => 0.5,
      'output' => 1,
    ),
    'ernie-lite-8k-0922' => 
    array (
      'input' => 0.016,
      'output' => 0.032,
    ),
    'ernie-lite-8k-0308' => 
    array (
      'input' => 0.006,
      'output' => 0.012,
    ),
    'gemini-3.1-pro-low' => 
    array (
      'input' => 2,
      'output' => 12,
    ),
    'chatgpt-4o-latest' => 
    array (
      'input' => 5,
      'output' => 15,
    ),
    'gpt-4o-2024-05-13' => 
    array (
      'input' => 5,
      'output' => 15,
    ),
    'gpt-4o-2024-08-06' => 
    array (
      'input' => 2.5,
      'output' => 10,
    ),
    'gpt-4o-2024-11-20' => 
    array (
      'input' => 2.5,
      'output' => 10,
    ),
    'o1-pro-2025-03-19' => 
    array (
      'input' => 150,
      'output' => 600,
    ),
    'o3-pro-2025-06-10' => 
    array (
      'input' => 20,
      'output' => 80,
    ),
    'gpt-5-chat-latest' => 
    array (
      'input' => 1.25,
      'output' => 10,
    ),
    'codex-auto-review' => 
    array (
      'input' => 1.75,
      'output' => 14,
    ),
    'gpt-3.5-turbo-16k' => 
    array (
      'input' => 3,
      'output' => 6,
    ),
    'claude-sonnet-4-6' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'ernie-3.5-8k-0205' => 
    array (
      'input' => 0.048,
      'output' => 0.048,
    ),
    'ernie-3.5-8k-1222' => 
    array (
      'input' => 0.024,
      'output' => 0.024,
    ),
    'ernie-3.5-4k-0205' => 
    array (
      'input' => 0.024,
      'output' => 0.024,
    ),
    'command-r-08-2024' => 
    array (
      'input' => 0.15,
      'output' => 0.6,
    ),
    'deepseek-reasoner' => 
    array (
      'input' => 1.1,
      'output' => 1.1,
    ),
    'claude-3-5-sonnet' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'claude-3-7-sonnet' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'claude-sonnet-4-5' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'o3-deep-research' => 
    array (
      'input' => 10,
      'output' => 40,
    ),
    'gpt-5-2025-08-07' => 
    array (
      'input' => 1.25,
      'output' => 10,
    ),
    'claude-haiku-4-5' => 
    array (
      'input' => 1,
      'output' => 5,
    ),
    'ernie-speed-128k' => 
    array (
      'input' => 0.008,
      'output' => 0.016,
    ),
    'gemini-2.0-flash' => 
    array (
      'input' => 0.1,
      'output' => 0.4,
    ),
    'gemini-2.5-flash' => 
    array (
      'input' => 0.3,
      'output' => 2.5,
    ),
    'gemini-pro-agent' => 
    array (
      'input' => 2,
      'output' => 12,
    ),
    'yi-34b-chat-0205' => 
    array (
      'input' => 0.36,
      'output' => 0.36,
    ),
    'yi-34b-chat-200k' => 
    array (
      'input' => 1.728,
      'output' => 1.728,
    ),
    'yi-large-preview' => 
    array (
      'input' => 40,
      'output' => 40,
    ),
    'grok-3-mini-beta' => 
    array (
      'input' => 0.3,
      'output' => 0.3,
    ),
    'grok-vision-beta' => 
    array (
      'input' => 5,
      'output' => 5,
    ),
    'grok-3-fast-beta' => 
    array (
      'input' => 5,
      'output' => 5,
    ),
    'claude-3-5-haiku' => 
    array (
      'input' => 1,
      'output' => 5,
    ),
    'gemini-1.5-flash' => 
    array (
      'input' => 0.15,
      'output' => 0.6,
    ),
    'grok-code-fast-1' => 
    array (
      'input' => 0.2,
      'output' => 1.5,
    ),
    'gpt-4.5-preview' => 
    array (
      'input' => 75,
      'output' => 150,
    ),
    'claude-opus-4-6' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'claude-opus-4-7' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'claude-opus-4-8' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'embedding_s1_v1' => 
    array (
      'input' => 0.143,
      'output' => 0.143,
    ),
    'command-nightly' => 
    array (
      'input' => 1,
      'output' => 4,
    ),
    'claude-3-sonnet' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'claude-sonnet-4' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'claude-opus-4-1' => 
    array (
      'input' => 15,
      'output' => 75,
    ),
    'gpt-4-32k-0613' => 
    array (
      'input' => 60,
      'output' => 120,
    ),
    'o3-mini-medium' => 
    array (
      'input' => 1.1,
      'output' => 4.4,
    ),
    'claude-fable-5' => 
    array (
      'input' => 10,
      'output' => 50,
    ),
    'ernie-speed-8k' => 
    array (
      'input' => 0.008,
      'output' => 0.016,
    ),
    'gemini-2.5-pro' => 
    array (
      'input' => 1.25,
      'output' => 10,
    ),
    'gemini-3-flash' => 
    array (
      'input' => 0.5,
      'output' => 3,
    ),
    'glm-4-alltools' => 
    array (
      'input' => 0.2,
      'output' => 0.2,
    ),
    'sparkdesk-v1.1' => 
    array (
      'input' => 2.5716,
      'output' => 2.5716,
    ),
    'sparkdesk-v2.1' => 
    array (
      'input' => 2.5716,
      'output' => 2.5716,
    ),
    'sparkdesk-v3.1' => 
    array (
      'input' => 2.5716,
      'output' => 2.5716,
    ),
    'sparkdesk-v3.5' => 
    array (
      'input' => 2.5716,
      'output' => 2.5716,
    ),
    'sparkdesk-v4.0' => 
    array (
      'input' => 2.5716,
      'output' => 2.5716,
    ),
    'yi-medium-200k' => 
    array (
      'input' => 24,
      'output' => 24,
    ),
    'yi-large-turbo' => 
    array (
      'input' => 24,
      'output' => 24,
    ),
    'command-r-plus' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'deepseek-coder' => 
    array (
      'input' => 0.54,
      'output' => 0.54,
    ),
    'claude-3-haiku' => 
    array (
      'input' => 0.25,
      'output' => 1.25,
    ),
    'gemini-1.5-pro' => 
    array (
      'input' => 2.5,
      'output' => 10,
    ),
    'grok-code-fast' => 
    array (
      'input' => 0.2,
      'output' => 1.5,
    ),
    'o1-2024-12-17' => 
    array (
      'input' => 15,
      'output' => 60,
    ),
    'o3-2025-04-16' => 
    array (
      'input' => 2,
      'output' => 8,
    ),
    'gpt-5.3-codex' => 
    array (
      'input' => 1.75,
      'output' => 14,
    ),
    'gpt-3.5-turbo' => 
    array (
      'input' => 0.5,
      'output' => 1,
    ),
    'ernie-tiny-8k' => 
    array (
      'input' => 0.002,
      'output' => 0.002,
    ),
    'chatglm_turbo' => 
    array (
      'input' => 0.7144,
      'output' => 0.7144,
    ),
    'command-light' => 
    array (
      'input' => 1,
      'output' => 4,
    ),
    'deepseek-chat' => 
    array (
      'input' => 0.54,
      'output' => 0.54,
    ),
    'grok-2-vision' => 
    array (
      'input' => 2,
      'output' => 2,
    ),
    'claude-3-opus' => 
    array (
      'input' => 15,
      'output' => 75,
    ),
    'claude-opus-4' => 
    array (
      'input' => 15,
      'output' => 75,
    ),
    'gpt-4.1-mini' => 
    array (
      'input' => 0.4,
      'output' => 0.8,
    ),
    'gpt-4.1-nano' => 
    array (
      'input' => 0.1,
      'output' => 0.2,
    ),
    'o3-mini-high' => 
    array (
      'input' => 1.1,
      'output' => 4.4,
    ),
    'gpt-5.4-mini' => 
    array (
      'input' => 0.75,
      'output' => 4.5,
    ),
    'ernie-4.0-8k' => 
    array (
      'input' => 0.24,
      'output' => 0.24,
    ),
    'ernie-3.5-8k' => 
    array (
      'input' => 0.024,
      'output' => 0.024,
    ),
    'ernie-bot-8k' => 
    array (
      'input' => 0.048,
      'output' => 0.048,
    ),
    'embedding-v1' => 
    array (
      'input' => 0.004,
      'output' => 0.004,
    ),
    'bge-large-zh' => 
    array (
      'input' => 0.004,
      'output' => 0.004,
    ),
    'bge-large-en' => 
    array (
      'input' => 0.004,
      'output' => 0.004,
    ),
    'chatglm_lite' => 
    array (
      'input' => 0.2858,
      'output' => 0.2858,
    ),
    '360gpt_s2_v9' => 
    array (
      'input' => 1.7144,
      'output' => 1.7144,
    ),
    '360gpt-turbo' => 
    array (
      'input' => 0.1716,
      'output' => 0.1716,
    ),
    'yi-large-rag' => 
    array (
      'input' => 50,
      'output' => 50,
    ),
    'gpt-image-1' => 
    array (
      'input' => 5,
      'output' => 40,
    ),
    'o3-mini-low' => 
    array (
      'input' => 1.1,
      'output' => 4.4,
    ),
    'gpt-4o-mini' => 
    array (
      'input' => 0.15,
      'output' => 0.6,
    ),
    'gpt-4-turbo' => 
    array (
      'input' => 10,
      'output' => 30,
    ),
    'chatglm_pro' => 
    array (
      'input' => 1.4286,
      'output' => 1.4286,
    ),
    'chatglm_std' => 
    array (
      'input' => 0.7144,
      'output' => 0.7144,
    ),
    'glm-3-turbo' => 
    array (
      'input' => 0.7144,
      'output' => 0.7144,
    ),
    'glm-4-flash' => 
    array (
      'input' => 0,
      'output' => 0,
    ),
    'glm-4v-plus' => 
    array (
      'input' => 0.02,
      'output' => 0.02,
    ),
    '360gpt2-pro' => 
    array (
      'input' => 1.7144,
      'output' => 1.7144,
    ),
    'grok-3-beta' => 
    array (
      'input' => 3,
      'output' => 3,
    ),
    'grok-4-fast' => 
    array (
      'input' => 0.2,
      'output' => 0.5,
    ),
    'grok-3-mini' => 
    array (
      'input' => 0.3,
      'output' => 0.5,
    ),
    'gpt-4o-all' => 
    array (
      'input' => 30,
      'output' => 60,
    ),
    'gpt-4-0613' => 
    array (
      'input' => 30,
      'output' => 60,
    ),
    'o1-preview' => 
    array (
      'input' => 15,
      'output' => 60,
    ),
    'gpt-5-mini' => 
    array (
      'input' => 0.25,
      'output' => 2,
    ),
    'gpt-5-nano' => 
    array (
      'input' => 0.05,
      'output' => 0.4,
    ),
    'glm-4-plus' => 
    array (
      'input' => 0.1,
      'output' => 0.1,
    ),
    'glm-4-0520' => 
    array (
      'input' => 0.2,
      'output' => 0.2,
    ),
    'glm-4-airx' => 
    array (
      'input' => 0.02,
      'output' => 0.02,
    ),
    'glm-4-long' => 
    array (
      'input' => 0.002,
      'output' => 0.002,
    ),
    'qwen-turbo' => 
    array (
      'input' => 1.7144,
      'output' => 1.7144,
    ),
    '360gpt-pro' => 
    array (
      'input' => 1.7144,
      'output' => 1.7144,
    ),
    'yi-vl-plus' => 
    array (
      'input' => 0.864,
      'output' => 0.864,
    ),
    'gpt-4-all' => 
    array (
      'input' => 30,
      'output' => 60,
    ),
    'gpt-4-32k' => 
    array (
      'input' => 60,
      'output' => 120,
    ),
    'bloomz-7b' => 
    array (
      'input' => 0.008,
      'output' => 0.008,
    ),
    'glm-4-air' => 
    array (
      'input' => 0.002,
      'output' => 0.002,
    ),
    'qwen-plus' => 
    array (
      'input' => 20,
      'output' => 20,
    ),
    'yi-medium' => 
    array (
      'input' => 5,
      'output' => 5,
    ),
    'yi-vision' => 
    array (
      'input' => 12,
      'output' => 12,
    ),
    'command-r' => 
    array (
      'input' => 0.5,
      'output' => 1.5,
    ),
    'grok-beta' => 
    array (
      'input' => 5,
      'output' => 5,
    ),
    'yi-large' => 
    array (
      'input' => 40,
      'output' => 40,
    ),
    'yi-spark' => 
    array (
      'input' => 2,
      'output' => 2,
    ),
    'gpt-4.1' => 
    array (
      'input' => 2,
      'output' => 4,
    ),
    'o1-mini' => 
    array (
      'input' => 1.1,
      'output' => 4.4,
    ),
    'o3-mini' => 
    array (
      'input' => 1.1,
      'output' => 4.4,
    ),
    'o4-mini' => 
    array (
      'input' => 1.1,
      'output' => 1.1,
    ),
    'gpt-5.2' => 
    array (
      'input' => 1.25,
      'output' => 10,
    ),
    'gpt-5.4' => 
    array (
      'input' => 2.5,
      'output' => 15,
    ),
    'gpt-5.5' => 
    array (
      'input' => 5,
      'output' => 30,
    ),
    'hunyuan' => 
    array (
      'input' => 14.286,
      'output' => 14.286,
    ),
    'command' => 
    array (
      'input' => 1,
      'output' => 4,
    ),
    'gpt-4o' => 
    array (
      'input' => 2.5,
      'output' => 10,
    ),
    'o1-pro' => 
    array (
      'input' => 150,
      'output' => 600,
    ),
    'o3-pro' => 
    array (
      'input' => 20,
      'output' => 80,
    ),
    'sonnet' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'tao-8k' => 
    array (
      'input' => 0.004,
      'output' => 0.004,
    ),
    'palm-2' => 
    array (
      'input' => 2,
      'output' => 2,
    ),
    'glm-4v' => 
    array (
      'input' => 0.1,
      'output' => 0.1,
    ),
    'grok-2' => 
    array (
      'input' => 2,
      'output' => 2,
    ),
    'grok-4' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'grok-3' => 
    array (
      'input' => 3,
      'output' => 15,
    ),
    'gpt-4' => 
    array (
      'input' => 30,
      'output' => 60,
    ),
    'gpt-5' => 
    array (
      'input' => 1.25,
      'output' => 10,
    ),
    'curie' => 
    array (
      'input' => 20,
      'output' => 20,
    ),
    'haiku' => 
    array (
      'input' => 1,
      'output' => 5,
    ),
    'glm-4' => 
    array (
      'input' => 14.286,
      'output' => 14.286,
    ),
    'opus' => 
    array (
      'input' => 5,
      'output' => 25,
    ),
    'ada' => 
    array (
      'input' => 20,
      'output' => 20,
    ),
    'o1' => 
    array (
      'input' => 15,
      'output' => 60,
    ),
    'o3' => 
    array (
      'input' => 2,
      'output' => 8,
    ),
  ),
  'cache_ratios' => 
  array (
    'claude-3-7-sonnet-20250219-thinking' => 0.1,
    'claude-sonnet-4-5-20250929-thinking' => 0.1,
    'claude-sonnet-4-20250514-thinking' => 0.1,
    'claude-opus-4-1-20250805-thinking' => 0.1,
    'claude-opus-4-5-20251101-thinking' => 0.1,
    'claude-opus-4-20250514-thinking' => 0.1,
    'gpt-4o-mini-realtime-preview' => 0.5,
    'gpt-4.5-preview-2025-02-27' => 0.5,
    'claude-3-5-sonnet-20240620' => 0.1,
    'claude-3-5-sonnet-20241022' => 0.1,
    'claude-3-7-sonnet-20250219' => 0.1,
    'claude-sonnet-4-5-20250929' => 0.1,
    'claude-3-5-haiku-20241022' => 0.1,
    'claude-haiku-4-5-20251001' => 0.1,
    'claude-3-sonnet-20240229' => 0.1,
    'claude-sonnet-4-20250514' => 0.1,
    'claude-opus-4-1-20250805' => 0.1,
    'claude-opus-4-5-20251101' => 0.1,
    'claude-opus-4-6-thinking' => 0.1,
    'claude-opus-4-7-thinking' => 0.1,
    'gpt-4o-realtime-preview' => 0.5,
    'claude-3-haiku-20240307' => 0.1,
    'gemini-3-flash-preview' => 0.1,
    'gemini-3.1-pro-preview' => 0.1,
    'gpt-4o-mini-2024-07-18' => 0.5,
    'claude-3-opus-20240229' => 0.1,
    'claude-opus-4-20250514' => 0.1,
    'claude-opus-4-6-medium' => 0.1,
    'claude-opus-4-7-medium' => 0.1,
    'o1-preview-2024-09-12' => 0.5,
    'gpt-5-mini-2025-08-07' => 0.1,
    'gpt-5-nano-2025-08-07' => 0.1,
    'claude-opus-4-7-xhigh' => 0.1,
    'gemini-3-pro-preview' => 0.1,
    'claude-opus-4-6-high' => 0.1,
    'claude-opus-4-7-high' => 0.1,
    'claude-opus-4-6-max' => 0.1,
    'claude-opus-4-6-low' => 0.1,
    'claude-opus-4-7-max' => 0.1,
    'claude-opus-4-7-low' => 0.1,
    'o1-mini-2024-09-12' => 0.5,
    'o3-mini-2025-01-31' => 0.5,
    'gpt-4o-2024-11-20' => 0.5,
    'gpt-4o-2024-08-06' => 0.5,
    'gpt-5-chat-latest' => 0.1,
    'deepseek-reasoner' => 0.25,
    'gpt-5-2025-08-07' => 0.1,
    'gpt-4.5-preview' => 0.5,
    'claude-opus-4-6' => 0.1,
    'claude-opus-4-7' => 0.1,
    'claude-sonnet-4' => 0.1,
    'deepseek-coder' => 0.25,
    'claude-haiku-4' => 0.1,
    'o1-2024-12-17' => 0.5,
    'deepseek-chat' => 0.25,
    'claude-opus-4' => 0.1,
    'gpt-4.1-mini' => 0.25,
    'gpt-4.1-nano' => 0.25,
    'gpt-5.4-mini' => 0.1,
    'gpt-4o-mini' => 0.5,
    'o1-preview' => 0.5,
    'gpt-5-mini' => 0.1,
    'gpt-5-nano' => 0.1,
    'claude-3' => 0.1,
    'o1-mini' => 0.5,
    'o3-mini' => 0.5,
    'gpt-4.1' => 0.25,
    'gpt-5.4' => 0.1,
    'gpt-5.5' => 0.1,
    'gpt-4o' => 0.5,
    'gpt-4' => 0.5,
    'gpt-5' => 0.1,
    'o1' => 0.5,
  ),
);
